import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
// const sidebars: SidebarsConfig = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

//   // But you can create a sidebar manually
//   /*
//   tutorialSidebar: [
//     'intro',
//     'hello',
//     {
//       type: 'category',
//       label: 'Tutorial',
//       items: ['tutorial-basics/create-a-document'],
//     },
//   ],
//    */
// };

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  aboutMeSidebar: {
    // {
    //   type: 'category',
    //   label: 'About me',
    //   items: ['about-me/about-me'],
    // },
    // {
    //   type: 'category',
    //   label: 'About me story',
    //   items: ['about-me/story'],
    // },

    // 'About me' : ['about-me/about-me']
    

},
tipsTricksSidebar: {
  'Git' : ['tips-tricks/git/git-alias' , 'tips-tricks/git/git-actions']
  
},
   
};

